import Footer from "./components/Footer";
import { raleway } from "./fonts";
import "./globals.css";

export const metadata = {
  title: "neinstok",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={raleway.variable}>
      <body
        className={`bg-gradient-to-b from-[#111317] via-[#1d2128] to-[#111317] min-h-screen font-raleway`}
      >
        {children}
      <Footer />
      </body>
    </html>
  );
}
