import { raleway } from "./fonts";
import "./globals.css";

export const metadata = {
  title: "neinstok",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={raleway.variable}>
      <body
        className={`bg-[#111317] min-h-screen font-raleway`}
      >
        {children}
      </body>
    </html>
  );
}
